<?php
/**
 * @author  Florian Palme <info@florian-palme.de>
 * @package FlorianPalme\OXIDVideos
 * @see
 */

namespace FlorianPalme\OXIDVideos\Application\Model;


use FlorianPalme\OXIDVideos\Core\Config;
use FlorianPalme\OXIDVideos\Core\Video;
use OxidEsales\Eshop\Core\Registry;

class Actions extends Actions_parent
{

    /**
     * can GetBannerUrl be executed?
     *
     * @var bool
     */
    protected $fpOXIDVideosExecuteGetBannerUrl = false;

    /**
     * Returns code to embed the category video
     *
     * @return string
     */
    public function fpOXIDVideosGetEmbedCode(): string
    {
        /** @var Config $config */
        $config = Registry::getConfig();

        $attributes = $config->fpOXIDVideosGetActionsConfig();

        if ($config->fpOXIDVideoGetConfigValue('fpoxidvideos_actions_poster')
            && $this->oxactions__oxpic->value) {
            $attributes['poster'] = $this->fpOXIDVideosGetBannerUrlForVideo();
        }

        /** @var Video $video */
        $video = oxNew(Video::class, $this->oxactions__fpoxidvideos_video->value, $attributes);

        return $video->getEmbedCode();
    }

    /**
     * Returns url to category image
     *
     * @return string
     */
    protected function fpOXIDVideosGetBannerUrlForVideo(): string
    {
        $this->fpOXIDVideosExecuteGetBannerUrl = true;

        $thumbUrl = $this->getBannerPictureUrl();

        $this->fpOXIDVideosExecuteGetBannerUrl = false;

        return $thumbUrl;
    }

    /**
     * @inheritDoc
     */
    public function getBannerPictureUrl()
    {
        /** @var Config $config */
        $config = Registry::getConfig();

        if ($this->oxactions__fpoxidvideos_video->value
            && $config->fpOXIDVideoGetConfigValue('fpoxidvideos_actions_poster')
            && !$this->fpOXIDVideosExecuteGetBannerUrl) {
            return '';
        }

        return parent::getBannerPictureUrl(); // TODO: Change the autogenerated stub
    }
}