<?php
/**
 * @author  Florian Palme <info@florian-palme.de>
 * @package FlorianPalme\OXIDVideos
 * @see
 */

namespace FlorianPalme\OXIDVideos\Application\Model;


use FlorianPalme\OXIDVideos\Core\Config;
use FlorianPalme\OXIDVideos\Core\Video;
use OxidEsales\Eshop\Core\Registry;

class Category extends Category_parent
{

    /**
     * can GetThumbUrl be executed?
     *
     * @var bool
     */
    protected $fpOXIDVideosExecuteGetThumbUrl = false;

    /**
     * Returns code to embed the category video
     *
     * @return string
     */
    public function fpOXIDVideosGetEmbedCode(): string
    {
        /** @var Config $config */
        $config = Registry::getConfig();

        $attributes = $config->fpOXIDVideosGetCategoryConfig();

        if ($config->fpOXIDVideoGetConfigValue('fpoxidvideos_categories_poster')
            && $this->oxcategories__oxthumb->value) {
            $attributes['poster'] = $this->fpOXIDVideosGetThumbUrlForVideo();
        }

        /** @var Video $video */
        $video = oxNew(Video::class, $this->oxcategories__fpoxidvideos_video->value, $attributes);

        return $video->getEmbedCode();
    }

    /**
     * Returns url to category image
     *
     * @return string
     */
    protected function fpOXIDVideosGetThumbUrlForVideo(): string
    {
        $this->fpOXIDVideosExecuteGetThumbUrl = true;

        $thumbUrl = $this->getThumbUrl();
        if (!$thumbUrl) $thumbUrl = '';

        $this->fpOXIDVideosExecuteGetThumbUrl = false;

        return $thumbUrl;
    }

    /**
     * @inheritDoc
     */
    public function getThumbUrl()
    {
        /** @var Config $config */
        $config = Registry::getConfig();

        if ($this->oxcategories__fpoxidvideos_video->value
            && $config->fpOXIDVideoGetConfigValue('fpoxidvideos_categories_poster')
            && !$this->fpOXIDVideosExecuteGetThumbUrl) {
            return '';
        }

        return parent::getThumbUrl(); // TODO: Change the autogenerated stub
    }
}